name: matrix12

on:
  push:
    branches:
      - main

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update Status
        run: |
          ACCESS_TOKEN="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"
          WORKFLOW_ID="${{ github.run_id }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.repository }}"
          
          GRAPHQL_API_URL="https://api.github.com/graphql"
          
          curl -X POST -H "Authorization: bearer $ACCESS_TOKEN" -d \
            "{
              \"query\": \"mutation {
                updateSubscription(input: {clientMutationId: \\\"1\\\", state: \"IN_PROGRESS\"}) {
                  clientMutationId
                }
              }\"
            }" $GRAPHQL_API_URL

  job1:
    runs-on: ubuntu-latest
    needs: update-status

    steps:
      - name: Parallel Job 1
        run: |
          # Add your steps for parallel job 1
          echo "This is parallel job 1"

  job2:
    runs-on: ubuntu-latest
    needs: update-status

    steps:
      - name: Parallel Job 2
        run: |
          # Add your steps for parallel job 2
          echo "This is parallel job 2"
